export const ENDPOINTS = {
  FEEDBACK: "/feedback",
  DECISIONS: "/decisions",
  DECISION_BY_ID: (id: string) => `/decisions/${encodeURIComponent(id)}`,
  SESSION_BY_ID: (id: string) => `/session/${encodeURIComponent(id)}`,
  EXPERIMENTS: "/experiments",
  EXPERIMENT_RESULTS: (id: string) => `/experiments/${encodeURIComponent(id)}/results`,
  EXPERIMENT_ROLLBACK: (id: string) => `/experiments/${encodeURIComponent(id)}/rollback`,
  CONSTRAINTS: "/constraints",
  EXPORT_DECISIONS: "/export/decisions",
  ROUTING_EXPLAIN: "/routing/explain",
  EVALUATIONS: "/evaluations",
  EVALUATION_BY_ID: (id: string) => `/evaluations/${encodeURIComponent(id)}`,
  EVALUATION_RESULTS: (id: string) => `/evaluations/${encodeURIComponent(id)}/results`,
  EVALUATION_CANCEL: (id: string) => `/evaluations/${encodeURIComponent(id)}/cancel`,
  FILES: "/files",
  FILE_BY_ID: (id: string) => `/files/${encodeURIComponent(id)}`,
  FILE_CONTENT: (id: string) => `/files/${encodeURIComponent(id)}/content`,
  BATCHES: "/batches",
  BATCH_BY_ID: (id: string) => `/batches/${encodeURIComponent(id)}`,
  BATCH_CANCEL: (id: string) => `/batches/${encodeURIComponent(id)}/cancel`,
} as const;
